ai_finding_writing_task:
  description: >
    finding are categorized into four elements: Condition, Criteria, Cause, Effect and Management Action. 
    The Condition refers to the actual state of affairs identified during the audit (what exists), 
    while the Criteria represent the standards or expectations (what should exist), which are used 
    to evaluate the condition. The Cause identifies the root reason for the difference between the 
    condition and criteria, answering why the issue occurred. The Effect outlines the risk 
    or consequence of the gap between condition and criteria, which can be either existing or 
    potential. And finally the Management Action, which summarize the needed management actions
    as practical, feasible solution to mitigate the risks identified in the finding to elicit a 
    positive action. Inline with above, write the audit finding that stratifies the above conditions.


  expected_output: >
    Title: 
    -->     Give a title that summarizes the finding.
    
    Finding:
    -->     Explain the finding while outlining the relation between {finding_condition}, {finding_criteria} and
    {finding_cause}; without explicitly stating the following words: condition, criteria and cause.

    Risks:
    -->    Explain the risk or consequence of the gap {finding_effect}.

    Management Action:
    -->    Suggest a management action inline with {management_action}
  agent: ai_finding_writer

gia_ai_finding_writing_task:
  description: >
      finding are categorized into four elements: Condition, Criteria, Cause, Effect and Management Action. 
      The Condition refers to the actual state of affairs identified during the audit (what exists), 
      while the Criteria represent the standards or expectations (what should exist), which are used 
      to evaluate the condition. The Cause identifies the root reason for the difference between the 
      condition and criteria, answering why the issue occurred. The Effect outlines the risk 
      or consequence of the gap between condition and criteria, which can be either existing or 
      potential. And finally the Management Action, which summarize the needed management actions
      as practical, feasible solution to mitigate the risks identified in the finding to elicit a 
      positive action. Inline with above, write the audit finding that stratifies the above conditions.

      The finding writeup should follow the following GIA finding writing guidelines:

        -Observation title should be short, clear, and non-negative.
        -Title should focus on the subject, not observation details.
        -Design a logical flow, keeping the reader in mind.
        -No detailed background; senior management already knows the business.
        -Keep observations direct and to the point, no long stories.
        -Avoid using personal pronouns ("I", "we", "us", "them") and subjective language (e.g. "believe", "think").
        -Use simple, plain English; avoid complicated sentences.
        -Group related points to make sentences shorter.
        -Define abbreviations when first mentioned.
        -Avoid judgmental language.
        -Do not start with "this circular/policy states that"; focus on risk-based observations.
        -Read for grammar and logical flow.
        -Anticipate and address possible reader questions.
        -Use “based on the review of this…” instead of "while reviewing/auditing".
        -Avoid system or area-specific terminology unless essential.
        -Start with a brief introduction on the finding, risk, and impact.
        -Maintain logical flow in bullet points; use sub-bullets as needed.
        -Ensure parallelism and consistency in bullet points.
        -Use commas correctly and frequently.
        -Avoid using multiple transition words ("however", "but", "nevertheless") in the same sentence.
        -Prefer passive voice for clarity, as long as grammar is correct.
        -Provide a complete story, addressing root cause and impact.
        -Avoid using words like “should”, “must” -  use "is supposed to" if necessary.
        -Make root causes clear without explicitly stating "root cause".
        -Avoid repetitive transitional phrases like "furthermore", "in addition", etc.
        -Use past perfect tense only when necessary.
        Be clear on:
            -Meaning of the issue.
            -Resulting risks.
            -Root cause.
            -Compensating controls.
            -Monitoring or exception reports.
            -System issues (if any).
            -Time frame  of the issue.
            -Impact assessment.
      

  expected_output: >
    Title: 
    -->     Give a title that summarizes the finding.
    
    Finding:
    --->     Explain the finding while outlining the relation between {finding_condition}, {finding_criteria} and
    {finding_cause}, without explicitly stating the following words: condition, criteria and cause.

    Risks:
    -->    Explain the risk or consequence of the gap {finding_effect}.

    Management Action:
    -->    Suggest a management action inline with {management_action}
  agent: gia_ai_finding_writer
